Models/Attendance.cs
using EmployeeDepartmentCRUDApp.Enums;
using EmployeeDepartmentCRUDApp.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeDepartmentCRUDApp.Models
{
    public class Attendance
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("Employee")]
        [Display(Name = "Employee")]
        [Required(ErrorMessage = "Please select employee")]
        public int EmployeeId { get; set; }
        public Employee? Employee { get; set; }

        [Required(ErrorMessage = "Date is required")]
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [Required(ErrorMessage = "Check In Time is required")]
        [Display(Name = "Check In Time")]
        [DataType(DataType.Time)]
        public DateTime CheckInTime { get; set; }
        [Required(ErrorMessage = "Check Out Time is required")]
        [Display(Name = "Check Out Time")]
        [DataType(DataType.Time)]
        public DateTime CheckOutTime { get; set; }
        [Required(ErrorMessage = "Please select status")]
        [Display(Name = "Status")]
        public Status Status { get; set; }
    }
}

Controllers/AttendanceController.cs
using EmployeeDepartmentCRUDApp.Enums;
using EmployeeDepartmentCRUDApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml.Style;
using OfficeOpenXml;

namespace EmployeeDepartmentCRUDApp.Controllers
{
    public class AttendanceController : BaseController
    {
        private readonly ApplicationDbContext _context;
        public AttendanceController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var attendances = await _context.Attendances.Include(e => e.Employee).ToListAsync();
            return View(attendances);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName");
            ViewBag.Status = Enum.GetValues(typeof(Status))
                           .Cast<Status>()
                           .Select(e => new SelectListItem
                           {
                               Value = ((int)e).ToString(),
                               Text = e.ToString()
                           }).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Attendance attendance)
        {  
            if (ModelState.IsValid)
            {
                _context.Attendances.Add(attendance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName", attendance.EmployeeId);
            ViewBag.Status = Enum.GetValues(typeof(Status))
                          .Cast<Status>()
                          .Select(e => new SelectListItem
                          {
                              Value = ((int)e).ToString(),
                              Text = e.ToString()
                          }).ToList();
            return View(attendance);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var attendance = await _context.Attendances.Include(e => e.Employee).FirstOrDefaultAsync(a => a.Id == id);
            if (attendance == null)
            {
                return NotFound();
            }
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName", attendance.EmployeeId);
            ViewBag.Status = Enum.GetValues(typeof(Status))
                     .Cast<Status>()
                     .Select(e => new SelectListItem
                     {
                         Value = ((int)e).ToString(),
                         Text = e.ToString()
                     }).ToList();
            return View(attendance);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Attendance attendance)
        {
            if (ModelState.IsValid)
            {
                _context.Attendances.Update(attendance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName", attendance.EmployeeId);
            ViewBag.Status = Enum.GetValues(typeof(Status))
                     .Cast<Status>()
                     .Select(e => new SelectListItem
                     {
                         Value = ((int)e).ToString(),
                         Text = e.ToString()
                     }).ToList();
            return View(attendance);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var attendance = await _context.Attendances.Include(e => e.Employee).FirstOrDefaultAsync(a => a.Id == id);
            if (attendance == null)
            {
                return NotFound();
            }
            return View(attendance);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var attendance = await _context.Attendances.Include(e => e.Employee).FirstOrDefaultAsync(a => a.Id == id);
            if (attendance == null)
            {
                return NotFound();
            }
            _context.Attendances.Remove(attendance);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Export()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            var attendances = _context.Attendances.Include(e => e.Employee)
                .Select(a => new Attendance
                {
                    Id = a.Id,
                    Employee = a.Employee,
                    Date = a.Date,
                    CheckInTime = a.CheckInTime,
                    CheckOutTime = a.CheckOutTime,
                    Status = a.Status
                })
                .ToList();

            using var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add("Attendances");

            // Add header
            worksheet.Cells[1, 1].Value = "ID";
            worksheet.Cells[1, 2].Value = "Employee";
            worksheet.Cells[1, 3].Value = "Date";
            worksheet.Cells[1, 4].Value = "Check In Time";
            worksheet.Cells[1, 5].Value = "Check Out Time";
            worksheet.Cells[1, 6].Value = "Status";

            // Format header
            using (var range = worksheet.Cells[1, 1, 1, 6])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
            }

            // Add data
            for (int i = 0; i < attendances.Count; i++)
            {
                var attend = attendances[i];
                worksheet.Cells[i + 2, 1].Value = attend.Id;
                worksheet.Cells[i + 2, 2].Value = attend.Employee?.EmployeeName;
                var dateCell = worksheet.Cells[i + 2, 3];
                dateCell.Value = attend.Date;
                dateCell.Style.Numberformat.Format = "dd-MM-yyyy";
                var timeCell = worksheet.Cells[i + 2, 4];
                timeCell.Value = attend.CheckInTime;
                timeCell.Style.Numberformat.Format = "hh:mm AM/PM";
                var timeCell2 = worksheet.Cells[i + 2, 5];
                timeCell2.Value = attend.CheckOutTime;
                timeCell2.Style.Numberformat.Format = "hh:mm AM/PM";
                worksheet.Cells[i + 2, 6].Value = attend.Status;
            }

            worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();

            var stream = new MemoryStream();
            package.SaveAs(stream);
            stream.Position = 0;

            var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            var fileName = $"Attendances_{DateTime.Today.Date.ToString("dd_MM_yyyy")}.xlsx";

            return File(stream, contentType, fileName);
        }
    }
}

Controllers/LeaveController.cs
using EmployeeDepartmentCRUDApp.Enums;
using EmployeeDepartmentCRUDApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml.Style;
using OfficeOpenXml;

namespace EmployeeDepartmentCRUDApp.Controllers
{
    public class LeaveController : BaseController
    {
        private readonly ApplicationDbContext _context;
        public LeaveController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var leaves = await _context.Leaves.Include(e => e.Employee).ToListAsync();
            return View(leaves);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName");
            ViewBag.LeaveTypes = Enum.GetValues(typeof(LeaveType))
                                .Cast<LeaveType>()
                                .Select(e => new SelectListItem
                                {
                                    Value = ((int)e).ToString(),
                                    Text = e.ToString()
                                }).ToList();
            ViewBag.Status = Enum.GetValues(typeof(Status))
                     .Cast<Status>()
                     .Select(e => new SelectListItem
                     {
                         Value = ((int)e).ToString(),
                         Text = e.ToString()
                     }).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Leave leave)
        {
            
            if (ModelState.IsValid)
            {
                leave.Employee = await _context.Employees.FindAsync(leave.EmployeeId);
                _context.Leaves.Add(leave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName", leave.EmployeeId);
            ViewBag.LeaveTypes = Enum.GetValues(typeof(LeaveType))
                            .Cast<LeaveType>()
                            .Select(e => new SelectListItem
                            {
                                Value = ((int)e).ToString(),
                                Text = e.ToString()
                            }).ToList();
            ViewBag.Status = Enum.GetValues(typeof(Status))
                     .Cast<Status>()
                     .Select(e => new SelectListItem
                     {
                         Value = ((int)e).ToString(),
                         Text = e.ToString()
                     }).ToList();
            return View(leave);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var leave = await _context.Leaves.Include(e => e.Employee).FirstOrDefaultAsync(a => a.Id == id);
            if (leave == null)
            {
                return NotFound();
            }
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName", leave.EmployeeId);
            ViewBag.LeaveTypes = Enum.GetValues(typeof(LeaveType))
                             .Cast<LeaveType>()
                             .Select(e => new SelectListItem
                             {
                                 Value = ((int)e).ToString(),
                                 Text = e.ToString()
                             }).ToList();
            ViewBag.Status = Enum.GetValues(typeof(Status))
                     .Cast<Status>()
                     .Select(e => new SelectListItem
                     {
                         Value = ((int)e).ToString(),
                         Text = e.ToString()
                     }).ToList();
            return View(leave);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Leave leave)
        {
            if (ModelState.IsValid)
            {
                leave.Employee = await _context.Employees.FindAsync(leave.EmployeeId);
                _context.Leaves.Update(leave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Employees = new SelectList(_context.Employees, "Id", "EmployeeName", leave.EmployeeId);
            ViewBag.LeaveTypes = Enum.GetValues(typeof(LeaveType))
                             .Cast<LeaveType>()
                             .Select(e => new SelectListItem
                             {
                                 Value = ((int)e).ToString(),
                                 Text = e.ToString()
                             }).ToList();
            ViewBag.Status = Enum.GetValues(typeof(Status))
                     .Cast<Status>()
                     .Select(e => new SelectListItem
                     {
                         Value = ((int)e).ToString(),
                         Text = e.ToString()
                     }).ToList();
            return View(leave);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var leave = await _context.Leaves.Include(e => e.Employee).FirstOrDefaultAsync(a => a.Id == id);
            if (leave == null)
            {
                return NotFound();
            }
            return View(leave);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leave = await _context.Leaves.Include(e => e.Employee).FirstOrDefaultAsync(a => a.Id == id);
            if (leave == null)
            {
                return NotFound();
            }
            _context.Leaves.Remove(leave);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Export()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            var leaves = _context.Leaves.Include(e => e.Employee)
                .Select(l => new Leave
                {
                    Id = l.Id,
                    Employee = l.Employee,
                    StartDate = l.StartDate,
                    EndDate = l.EndDate,
                    LeaveType = l.LeaveType,
                    Reason = l.Reason,
                    Status = l.Status
                })
                .ToList();

            using var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add("Leaves");

            // Add header
            worksheet.Cells[1, 1].Value = "ID";
            worksheet.Cells[1, 2].Value = "Employee";
            worksheet.Cells[1, 3].Value = "Start Date";
            worksheet.Cells[1, 4].Value = "End Date";
            worksheet.Cells[1, 5].Value = "Leave Type";
            worksheet.Cells[1, 6].Value = "Leave Reason";
            worksheet.Cells[1, 7].Value = "Status";

            // Format header
            using (var range = worksheet.Cells[1, 1, 1, 7])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
            }

            // Add data
            for (int i = 0; i < leaves.Count; i++)
            {
                var leave = leaves[i];
                worksheet.Cells[i + 2, 1].Value = leave.Id;
                worksheet.Cells[i + 2, 2].Value = leave.Employee?.EmployeeName;
                var dateCell = worksheet.Cells[i + 2, 3];
                dateCell.Value = leave.StartDate;
                dateCell.Style.Numberformat.Format = "dd-MM-yyyy";
                var dateCell2 = worksheet.Cells[i + 2, 4];
                dateCell2.Value = leave.StartDate;
                dateCell2.Style.Numberformat.Format = "dd-MM-yyyy";
                worksheet.Cells[i + 2, 5].Value = leave.LeaveType;
                worksheet.Cells[i + 2, 6].Value = leave.Reason;
                worksheet.Cells[i + 2, 7].Value = leave.Status;
            }

            worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();

            var stream = new MemoryStream();
            package.SaveAs(stream);
            stream.Position = 0;

            var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            var fileName = $"Leaves_{DateTime.Today.Date.ToString("dd_MM_yyyy")}.xlsx";

            return File(stream, contentType, fileName);
        }
    }
}

Views/Attendance/Create.cshtml
@{
    ViewData["Title"] = "Create Attendance";
}

@model EmployeeDepartmentCRUDApp.Models.Attendance

<div class="container-fluid">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h2 class="text-danger">Create Attendance</h2>
        </div>
     </div>
    <hr />
</div>

<div class="row">
    <div class="col-md-8 col-lg-6">
<form asp-action="Create" method="post" class="needs-validation" novalidate>
    <div class="mb-3">
        <label asp-for="EmployeeId" class="form-label"></label>
        <select asp-for="EmployeeId" asp-items="ViewBag.Employees" class="form-select">
            <option value="">Select Employee</option>
        </select>
        <span asp-validation-for="EmployeeId" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Date" class="form-label"></label>
        <input type="date" asp-for="Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CheckInTime" class="form-label"></label>
        <input type="time" asp-for="CheckInTime" class="form-control" />
        <span asp-validation-for="CheckInTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CheckOutTime" class="form-label"></label>
        <input type="time" asp-for="CheckOutTime" class="form-control" />
        <span asp-validation-for="CheckOutTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Status" class="form-label"></label>
        <select asp-for="Status" asp-items="ViewBag.Status" class="form-select">
            <option value="">Select Status</option>
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success btn-sm">Save</button>
</form>
</div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Attendance/Delete.cshtml
@{
    ViewData["Title"] = "Delete Attendance";
}
@model EmployeeDepartmentCRUDApp.Models.Attendance
<div class="container-fluid">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h2 class="text-danger">Delete Attendance</h2>
        </div>
    </div>
    <hr />
</div>

<div>
    <h4>Are you sure you want to delete these attendance?</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Employee Name</dt>
        <dd class="col-sm-10">@Model.Employee?.EmployeeName</dd>

        <dt class="col-sm-2">Date</dt>
        <dd class="col-sm-10">@Model.Date.ToString("dd/MM/yyyy")</dd>

        <dt class="col-sm-2">Check In Time</dt>
        <dd class="col-sm-10">@Model.CheckInTime</dd>

        <dt class="col-sm-2">Check Out Time</dt>
        <dd class="col-sm-10">@Model.CheckOutTime</dd>

        <dt class="col-sm-2">Status</dt>
        <dd class="col-sm-10">@Model.Status</dd>
    </dl>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-controller="Leave" asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>
</div>

Views/Attendance/Edit.cshtml
@{
    ViewData["Title"] = "Edit Attendance";
}

@model EmployeeDepartmentCRUDApp.Models.Attendance

<div class="container-fluid">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h2 class="text-danger">Edit Attendance</h2>
        </div>
    </div>
    <hr />
</div>

<div class="row">
    <div class="col-md-8 col-lg-6">
        <form asp-action="Edit" method="post" class="needs-validation" novalidate>
            <input type="hidden" asp-for="Id" />
            <div class="mb-3">
                <label asp-for="EmployeeId" class="form-label"></label>
                <select asp-for="EmployeeId" asp-items="ViewBag.Employees" class="form-select">
                    <option value="">Select Employee</option>
                </select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Date" class="form-label"></label>
                <input type="date" asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="CheckInTime" class="form-label"></label>
                <input type="time" asp-for="CheckInTime" class="form-control" />
                <span asp-validation-for="CheckInTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="CheckOutTime" class="form-label"></label>
                <input type="time" asp-for="CheckOutTime" class="form-control" />
                <span asp-validation-for="CheckOutTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Status" class="form-label"></label>
                <select asp-for="Status" asp-items="ViewBag.Status" class="form-select">
                    <option value="">Select Status</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success btn-sm">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Attendance/Index.cshtml
@{
    ViewData["Title"] = "Attendance List";
}
@model IEnumerable<EmployeeDepartmentCRUDApp.Models.Attendance>

<div class="container-fluid">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h2 class="text-danger">Attendance List</h2>
        </div>
        <div class="col-md-6 text-md-end mt-2 mt-md-0">
            <a class="btn btn-primary btn-sm me-2" asp-controller="Attendance" asp-action="Create">
                <i class="bi bi-plus-circle"></i> Create Attendance
            </a>
            <a class="btn btn-info btn-sm" asp-controller="Attendance" asp-action="Export">
                <i class="bi bi-download"></i> Export
            </a>
        </div>
    </div>
    <hr />
</div>

<div class="table-responsive">
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th scope="col">Sr.No</th>
            <th scope="col">Emp Name</th>
            <th scope="col">Date</th>
            <th scope="col">Check In Time</th>
            <th scope="col">Check Out Time</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var attend in Model.Select((entry, index) => new { entry, index }))
        {
            <tr>
                <td>@(attend.index + 1)</td>
                <td>@attend.entry.Employee?.EmployeeName</td>
                <td>@attend.entry.Date.ToString("dd/MM/yyyy")</td>
                <td>@attend.entry.CheckInTime.ToString("HH:mm tt")</td>
                <td>@attend.entry.CheckOutTime.ToString("HH:mm tt")</td>
                <td>@attend.entry.Status</td>
                <td>
                    <a class="btn btn-warning btn-sm mx-2" asp-controller="Attendance" asp-action="Edit" asp-route-id="@attend.entry.Id">Edit</a>
                    <a class="btn btn-danger btn-sm" asp-controller="Attendance" asp-action="Delete" asp-route-id="@attend.entry.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>